# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples
#


#.
#.
#.


alias setup.pdk="source /usr/local/bin/setup.pdk"
alias magic.run="source /usr/local/bin/magic.run"
export PATH="$PATH:/home/$USER/.local/bin"